# 本地开发/测试用，从源码构建
services:
  frontend:
    build: ./frontend
    container_name: yewtally-frontend
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: yewtally-backend
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
