# 本地开发/测试用，从源码构建
services:
  frontend:
    build: ./frontend
    container_name: yewtally-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: yewtally-backend
    volumes:
      - ./data:/app/data
    environment:
      - BIND_ADDR=:8080
      # - WEBHOOK_SECRET=your-webhook-secret
    restart: unless-stopped
